### ISSUE TITLE
document/implement COS compile/link process independent of GNU make

### ISSUE THREAD

**Issue by devel-chm** [CObjectSystem/COS#11]
The current COS build process requires GNU make 3.80 or above.  This is problematic for platforms that don't have a "friendly" posix-ish development environment like MS windows.  The lack of a standard shell for windows introduces incompatibilities in GNU make implementations due to the non-posix implementations.

After studying the build process and files in include/cos/mak I've determined that the basics of the build process appear to be:

1. run cosgen to produce XXX_gens.c if generics are being defined, add XXX_gens.o to OBJECTS
2. run cosprp to produce XXX_prps.c if properties are being defined, add XXX_prps.o to OBJECTS
3. after compiling all the files, run cossym to produce XXX_syms.c to compile and link with OBJECTS

It seems that a coscc script might be written to implement this process without requiring GNU make.  The GNU make build process could use this script to run the build.  It could also be used from other makes to build software using COS.

**Comment by ldeniau** [comment]
These points are correct, cosgen and cosprp are tools to automatize definitions from content, but they could/should be replace by manual definition from developers to simplify the compilation phase.

On the other hand, cossym is mandatory... It would be nice/better to have to automatic introspection of symbol on-demand...
