### ISSUE TITLE
wrong comment in algos.h

### ISSUE THREAD

**Issue by bkerin** [CObjectSystem/COS#13]
The comment for the first of these two is wrong.  It should say 'using space as separator' or maybe using empty string as separator or something.

// flatten tuple T to sequence using s as separator, i.e. (a,b,c) -> a b c
#define COS_PP_SEP(T) \
        COS_PP_FOLDL(T,,COS_PP_PAIR)

// flatten tuple T to sequence using s as separator, i.e. (a,b,c),; -> a ; b ; c
#define COS_PP_SEPWITH(T,s) \
        COS_PP_IF(COS_PP_2ARGS(COS_PP_ID T))( \
          COS_PP_ARG1 T COS_PP_SEP( \
            COS_PP_MAP2((COS_PP_REST T),(COS_PP_DUPSEQ_N(s)),COS_PP_SWAP)), \
          COS_PP_ID T)

**Comment by ldeniau** [comment]
corrected
