### ISSUE TITLE
many (probably harmless) warnings on gcc 7.2.0

### ISSUE THREAD

**Issue by bkerin** [CObjectSystem/COS#15]
$ make 2>&1 | grep --perl-regexp --only-matching '\[-W.*\=?.*\]' | sort | uniq --count
      7 [-Wimplicit-fallthrough=]
     30 [-Wunused-const-variable=]
  15984 [-Wunused-local-typedefs]

All the tests in make tests succeed and I guess these are probably warnings that have crept in with recent additions to -Wall in gcc.

For the last of these at least it seems likely that adding -Wno-usused-local-typedefs would be the solution.

**Comment by ldeniau** [comment]
I don't get any warning with gcc 12.2
