### ISSUE TITLE
COS/CosBase/examples/ex01/File.c behaves confusing with respect to 0 arg

### ISSUE THREAD

**Issue by bkerin** [CObjectSystem/COS#18]
COS/CosBase/examples/ex01/File.c contains:

defmethod(OBJ, ginitWithStr, File, (STR)str)
  self->file = str ? fopen(str,"r+") : stdout;
  if (!self->file)
    test_errno(); // THROW

  retmethod(_1);
endmethod

Using 0 caused me some confusion.  Seems like it should get "stdout" in the call as well to be clear.
Part of the confusion comes because using 0 causes stdout to get closed on grelease(strm), which causes e.g. printf() statement after this to show nothing.

This is an issue because the examples in CosBase and CosStd are the first things people are likely to try playing with in COS, so getting them as unsurprising as possible seems worthwhile.

**Comment by ldeniau** [comment]
fixed in 962e67e
