### ISSUE TITLE
lingering mentions/use of gdelete() and gAutoDelete()

### ISSUE THREAD

**Issue by bkerin** [CObjectSystem/COS#19]
From gitk it looks like they are removed but there are still a couple uses/mentions floating around.  I'm not sure if Vector_lzy.c isn't build or what.  Anyway here are the mentions:

$ pwd
/home/bkerin/tmp/COS
$ grep 'gautoDelete' -r *
CHANGELOG:  - gdelete and gautoDelete added (for semi-GC)
CosStd/src/tmpl/Vector_lzy.c:  retmethod( gautoDelete(VALOBJ(vec->value[i*vec->stride])) );
$ grep 'Delete' -r *
CHANGELOG:  - gdelete and gautoDelete added (for semi-GC)
CosStd/src/tmpl/Vector_lzy.c:  retmethod( gautoDelete(VALOBJ(vec->value[i*vec->stride])) );
CosStd/include/cos/gen/floatop.h:   new autoDelete object resulting from the promotion/coercion of _1
CosStd/include/cos/gen/numop.h:   new autoDelete object resulting from the promotion/coercion of _1
$

**Comment by ldeniau** [comment]
Thank you for pointing this out. Fixed.
