### ISSUE TITLE
Error when executing CosStd/examples/ex01

### ISSUE THREAD

**Issue by mingodad** [CObjectSystem/COS#2]
**\* functional sum (repeat + eval)
COS-Info [23583]: exiting with uncaught exception ExBadMessage 'gcopy(FunExpr2)' thrown at (src/Any.c:140)

**Comment by FedeOmoto** [comment]
Same here.

**Comment by devel-chm** [comment]
I get this error on cygwin64/win7 with the current git.  I have no idea how to start tracking this down.  Running under gdb was not particularly helpful---although I'm no expert.  Are there any tips or practices that were learned during the development and implementation of COS on how to start debugging this type of problem?

**Comment by devel-chm** [comment]
A few comments and printf's and I've narrowed the problem lines to:
`OBJ inc  = gautoRelease(aFunctor(gaddTo,0,aInt(1)));  // error here`
in the `sum_rep()` and `sum_itr()` routines.

For the `sum_oop()` routine, there is a SEGV at this line:
`  I32 x    = gint(greduce1(xs,aFunctor(gaddTo,0,0),aInt(0)));  // crashes here`

I don't know how to debug this type of problem.  I've been working through the code for main.c manually to try to understand how COS is working and where the problems happen.  Suggestions welcome.

**Comment by ldeniau** [comment]
Functors need to be reviewer, I think that it is overdesigned and should be simplified.
