### ISSUE TITLE
Should COS/CosStd/examples/ex01/Makefile use $(moddeps) for dependencies?

### ISSUE THREAD

**Issue by bkerin** [CObjectSystem/COS#20]
Currently this file contains:

  incdirs := ../../../CosBase/include ../../include .
  libdirs := ../../../CosBase/$(OSNAME)/lib ../../$(OSNAME)/lib

It might be nice if it did things more like the tests in CosStd instead:

  incdirs := $(foreach m,$(moddeps),../../../$(m)/include) .
  libdirs := $(foreach m,$(moddeps),../../../$(m)/$(OSNAME)/lib)

As this would show a general mechanism for pulling in modules.  Or maybe that isn't the preferred way for user-developed modules.

**Comment by ldeniau** [comment]
Fixed
