### ISSUE TITLE
applying $(wildcard) in CosBas/include/cos/mak/default causes silent failure on typo in defgens

### ISSUE THREAD

**Issue by bkerin** [CObjectSystem/COS#23]
looks like this was done in the individual Makefile but then it got moved into cos/mak/default like so:

     DEFGENS   = $(wildcard $(defgens))

This is sort of unfortunate because then a typo in a file name in `defgens :=` in a project Makefile
causes a silent failure to run cosgen at all.  From commit 2a8c83fbc37a08cf63aaedafdf0a463d9faa36c2
it looks like at some point projects just did $(wildcard) themselves if they wanted it and IMO that's a better way to go, as surprise application of wildcard to constant expressions is error-prone.  I guess since it was once done its probably still possible and late $(wildcard) on simply expanded variable content is not required for other reasons.  It works ok for me so far for my simple tests anyway.

**Comment by ldeniau** [comment]
no PR proposed, closing
