### ISSUE TITLE
COS port to windows

### ISSUE THREAD

**Issue by devel-chm** [CObjectSystem/COS#3]
I'm interested in using and/or contributing to COS but need a portable framework including windows.  Is the problem with a windows build a requirement of the library itself or is it due to the build process.  If the latter, there is MSYS for gnu-ish build and shell tools and gcc is available for windows as well.

**Comment by devel-chm** [comment]
Currently, I have a static build implementation of COS on cygwin and have implemented perl versions of the key utilities cosgen, cosprp, and cossym.  Once these are verified, I would like to extract the build process from the many gnu make files and implement a cos compiler wrapper that can be used to build COS applications without requiring GNU make to do the "compiling/linking" explicitly.

**Comment by devel-chm** [comment]
Update: the perl versions of cosgen, cosprp, and cossym are able to build COS, examples, and tests when used in place of the original shell scripts.  In theory it should now be possible to build COS programs on windows (maybe using GNU make).

**Comment by ldeniau** [comment]
your tools look promising, make a PR (if your are still interested)
