### ISSUE TITLE
Error compiling in GCC >=10:  multiple definition of cos_method_trace

### ISSUE THREAD

**Issue by nicholascarroll** [CObjectSystem/COS#34]
Try to build this project on Linux with GCC 10 and `make` fails with:
Linux/release/CosBase_prps.o:(.bss+0x8): multiple definition of `cos_method_trace

GCC 10 defaults to -fno-common which is what is producing this error. 
as described here:
https://gcc.gnu.org/gcc-10/porting_to.html#common

**Comment by ldeniau** [comment]
Fixed in commit f4645cd
