### ISSUE TITLE
Add support for MSYS2 MSYS

### ISSUE THREAD

**Issue by ghost** [CObjectSystem/COS#37]
`uname -s` on `MSYS2 MSYS Shell` on my system is `MSYS_NT-6.3-9600`. Only the part `MSYS_NT` should be considered and used as the key to detect `MSYS2 MSYS`. The later part is Windows versions (that would change from system to system).

Note: `MSYS2 MSYS` is a fork of Cygwin. MSYS2 project provided several Shells, each Shell is a separate environment.

**Comment by ghost** [comment]
@ldeniau Added on #49. This issue could be closed.

**Comment by ldeniau** [comment]
I don't use these platforms, propose PR to solve your issue.
