### ISSUE TITLE
Add support for MSYS2 MINGW64

### ISSUE THREAD

**Issue by ghost** [CObjectSystem/COS#38]
`uname -s` on `MSYS2 MINGW64 Shell` on my system is `MINGW64_NT-6.3-9600`. Only the part `MINGW64_NT` should be considered and used as the key to detect `MSYS2 MINGW64`. The later part is Windows versions (that would change from system to system).

Note: `MSYS2 MINGW64` targets native Windows without POSIX compatibility, unlike `MSYS2 MSYS`. MSYS2 project provided several Shells, each Shell is a separate environment.

**Comment by ghost** [comment]
@ldeniau Added on #49. This issue could be closed.

**Comment by ldeniau** [comment]
I don't use these platforms, propose PR to solve your issue.
