### ISSUE TITLE
uname -s shouldn't be used directly for OSNAME

### ISSUE THREAD

**Issue by ghost** [CObjectSystem/COS#39]
For example, `CYGWIN_NT` is enough for detection of Cygwin.

Related issues: https://github.com/CObjectSystem/COS/issues/37 https://github.com/CObjectSystem/COS/issues/38

**Comment by 2dpdlja496or43iq** [comment]
Of course `uname -s` shouldn't be used as the only way to determine the platforms. What if there is no Bash shell at all like on pure Windows environment?

https://github.com/CObjectSystem/COS/issues/43
https://github.com/CObjectSystem/COS/issues/44
https://github.com/CObjectSystem/COS/issues/45
https://github.com/CObjectSystem/COS/issues/46
https://github.com/CObjectSystem/COS/issues/47

**Comment by ghost** [comment]
@ldeniau Fixed on #49. This issue could be closed.

**Comment by ldeniau** [comment]
I don't use these platforms, propose PR to solve your issue.
