### ISSUE TITLE
This information is wrong! It doesn't work on MSYS2!

### ISSUE THREAD

**Issue by ghost** [CObjectSystem/COS#40]
README said MSYS2 was a tested platform:

https://github.com/CObjectSystem/COS/blob/c5597c30e2ce4f97465cb31dfaad66a2d5efd063/README#L132

But the fact is it doesn't work on MSYS2! It doesn't work on any Shells of MSYS2!

On MSYS2 MSYS Shell:

```
CosBase/include/cos/prologue:113: CosBase/include/cos/cfg/MSYS_NT-6.3-9600: No such file or directory
make: *** No rule to make target 'CosBase/include/cos/cfg/MSYS_NT-6.3-9600'.  Stop.
```

On MSYS2 MINGW64 Shell:

```
CosBase/include/cos/prologue:113: CosBase/include/cos/cfg/MINGW64_NT-6.3-9600: No such file or directory
make: *** No rule to make target 'CosBase/include/cos/cfg/MINGW64_NT-6.3-9600'.  Stop.
```

**Comment by ldeniau** [comment]
It was tested on MSYS2 12-15 years around 2008-2010 when I wrote the papers.

**Comment by ldeniau** [comment]
You are welcome to propose a fix, I don't have access anymore to windows+msys2 machines. And I don't have the time to support windows anyway.
