### ISSUE TITLE
Support for MSYS2

### ISSUE THREAD

**Issue by 2dpdlja496or43iq** [CObjectSystem/COS#42]
It's not as simple as copying the config for Cygwin and adapt it for MSYS2. I tried, but for unknown reasons, it still said it can't find the config files for MSYS2 even though they are right there, next to other config files for other systems. I also found there is no Windows support at all (I mean MSVC because MSVC is the official compiler for Windows), so far I only see Unix or Unix emumation (Cygwin). I examined the config file for Cygwin and I found:

```
#
# system specific
#
SYSFLAGS    := -DOSNAME=$(OSNAME) \
               -D_XOPEN_SOURCE=500 -D_REENTRANT -D_THREAD_SAFE \
               -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE
```

Defining ` -DOSNAME=$(OSNAME)` directly like that means there is hard coded adaptions for `$(OSNAME)` on source code level. So it's definitely not as simple as copying the config for Cygwin and adapt it for MSYS2 could make it work on MSYS2.

**Comment by 2dpdlja496or43iq** [comment]
MSYS2 has many environments: https://www.msys2.org/docs/environments/

Support for MSYS2 means supporting all of these environments, so this ticket also included these tickets: https://github.com/CObjectSystem/COS/issues/37 https://github.com/CObjectSystem/COS/issues/38

**Comment by ghost** [comment]
@ldeniau Added on #49. This issue could be closed.

**Comment by ldeniau** [comment]
I don't use these platforms, propose PR to solve your issue.
