### ISSUE TITLE
Support Borland C

### ISSUE THREAD

**Issue by 2dpdlja496or43iq** [CObjectSystem/COS#46]
Free compiler (32 bit only):

https://www.embarcadero.com/free-tools/ccompiler

C++ Builder Community Edition:

https://www.embarcadero.com/products/cbuilder/starter

**Comment by ghost** [comment]
This is impossible because COS needs a POSIX shell to work. This issue could be closed as not planned @ldeniau

**Comment by ldeniau** [comment]
I don't use these platforms, propose PR to solve your issue.
