### ISSUE TITLE
Support standalone MinGW-w64 compilers

### ISSUE THREAD

**Issue by 2dpdlja496or43iq** [CObjectSystem/COS#47]
There is no Bash shell like MSYS2 so it's a separate issue from MSYS2: https://github.com/CObjectSystem/COS/issues/42

https://winlibs.com/

https://github.com/niXman/mingw-builds-binaries/releases

https://github.com/mstorsjo/llvm-mingw/releases

**Comment by ghost** [comment]
This is impossible because COS needs a POSIX shell to work. This issue could be closed as not planned @ldeniau

**Comment by ldeniau** [comment]
I don't use these platforms, propose PR to solve your issue.
