### ISSUE TITLE
Support w64devkit

### ISSUE THREAD

**Issue by 2dpdlja496or43iq** [CObjectSystem/COS#48]
https://github.com/skeeto/w64devkit

w64devkit is based on busybox-w32: https://github.com/rmyorston/busybox-w32

`uname -s` on busybox-w32 will report `Windows_NT`, it's a fixed string on Windows so it's easier to support than the dynamic result of `uname -s` on Cygwin/MSYS2 as they also incorporate Windows version into the strings (so `uname -s` on MSYS2/Windows 7 will different from `uname -s` on MSYS2/Windows 10).

**Comment by ghost** [comment]
This is impossible as w64devkit is not a complete POSIX environment like Cygwin or MSYS2. The busybox-w32 utilities are also not compatible with their GNU counterparts and they are missing many features. This issue could be closed as not planned @ldeniau

**Comment by ldeniau** [comment]
I don't use these platforms, propose PR to solve your issue.
