### ISSUE TITLE
mak/program $(TARGET).run fails on cygwin for make tests

### ISSUE THREAD

**Issue by devel-chm** [CObjectSystem/COS#7]
It appears the problem is in the # rules for running shared program (helper)
and the creation of the appropriate environment to run the tests being compiled.
Will continue to track down the issue but opening this ticket to track the problem.

**Comment by devel-chm** [comment]
I don't clearly understand the makefile logic but the problem appears to be that the program makefile is using the target.run rather than target.srun to run the tests code on CYGWIN_NT-6.1.  I am able to run the tests program from the CYGWIN_NT-6.1/bin directory by hand.  I'm attaching logs from make and make tests.

[cos-make-tests-cygwin-log.txt](https://github.com/CObjectSystem/COS/files/275030/cos-make-tests-cygwin-log.txt)
[cos-make-cygwin-log.txt](https://github.com/CObjectSystem/COS/files/275029/cos-make-cygwin-log.txt)

**Comment by devel-chm** [comment]
I finally figured out the problem:  the Makefile files for the tests and examples have the targets hardwired to release.run.  Ideally for configurations with static libraries, release.srun or some equivalent should be called instead.  I'm not sure where to fix the makefiles for that thought.

**Comment by ldeniau** [comment]
Makefiles are overdesigned, making them difficult to use or extend. It's my feeling today as I forgot how they work. Should be simplified/redesigned.
